from enum import Enum

class RetrievalMethod(str, Enum):
    VECTOR = "vector"
    KEYWORD = "keyword"
    HYBRID = "hybrid"

class FailureMode(str, Enum):
    LOW_CONTEXT_PRECISION = "LOW_CONTEXT_PRECISION"
    LOW_CONTEXT_RECALL = "LOW_CONTEXT_RECALL"
    LOW_FAITHFULNESS = "LOW_FAITHFULNESS"
    LOW_ANSWER_RELEVANCY = "LOW_ANSWER_RELEVANCY"
    STALE_INDEX = "STALE_INDEX"
    POOR_CHUNKING = "POOR_CHUNKING"
    DUPLICATE_CONTEXT = "DUPLICATE_CONTEXT"
    CROSS_DOCUMENT_ENTITY_COLLAPSE = "CROSS_DOCUMENT_ENTITY_COLLAPSE"
    SINGLE_HOP_BLINDNESS = "SINGLE_HOP_BLINDNESS"
    MULTI_HOP_FAILURE = "MULTI_HOP_FAILURE"
    RERANKING_FAILURE = "RERANKING_FAILURE"
    EMBEDDING_MISMATCH = "EMBEDDING_MISMATCH"
    CITATION_FAILURE = "CITATION_FAILURE"
    CONTEXT_FRAGMENTATION = "CONTEXT_FRAGMENTATION"

class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class RepairType(str, Enum):
    RECHUNK = "RECHUNK"
    REINDEX = "REINDEX"
    HYBRID_RETRIEVAL = "HYBRID_RETRIEVAL"
    RERANK = "RERANK"
    DEDUPLICATE = "DEDUPLICATE"
    CITATION_VALIDATION = "CITATION_VALIDATION"
    QUERY_DECOMPOSITION = "QUERY_DECOMPOSITION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
